### ISSUE TITLE
RateLimitError: unusual activity detected.

### ISSUE THREAD

**Issue by ARajgor** [elevenlabs/elevenlabs-python#119]
I'm starting with elevenlabs using python. but I'm getting error.

```
from elevenlabs import generate, play, save, set_api_key

set_api_key('API_KEY')

audio = generate(
    text="Hello World",
    voice="Bella",
    model="eleven_multilingual_v2",
)

save(audio, "hello_world.wav")

```

after the first request, I'm getting this error,

```
elevenlabs.api.error.RateLimitError: Unusual activity detected. Free Tier usage disabled. 

If you are using proxy/VPN you might need to purchase a Paid Plan to not trigger our abuse detectors.
Free Tier only works if users do not abuse it, for example by creating multiple free accounts. 
If we notice that many people try to abuse it, we will need to reconsider Free Tier altogether. Please play fair.
Please purchase any Paid Subscription to continue.
```

I only created an account on Elevenlab and till now I used the website for my work. today is the first time I have used API. What should I do? I'm just using it for personal project.

**Comment by navi504** [comment]
Having this issue too, api key works on collab but not with python sdk

**Comment by dsinghvi** [comment]
@ARajgor this happens occasionally if you hit the API several times and are not on a paid account. We've just released a new SDK published as a beta version ([0.3.0b0](https://github.com/elevenlabs/elevenlabs-python?tab=readme-ov-file#%EF%B8%8F-install)) where you can directly pass in your `api_key` to the generate function. Do you mind passing in your api key and seeing if the issue still persists?

**Comment by osama-obo-tnt** [comment]
@dsinghvi The issue is still there even with the paid API, it often works locally on VS code and local API by postman but 
 I deployed it on streamlit it threw same error (free tier is ...) and even deployed on pythonanywhere.com but same result , why it is throwing error on paid API ??
Error :  {"error":"status_code: 401, body: {'detail': {'status': 'detected_unusual_activity', 'message': 'Unusual activity detected. Free Tier usage disabled. If you are using a proxy/VPN you might need to purchase a Paid Plan to not trigger our abuse detectors. Free Tier only works if users do not abuse it, for example by creating multiple free accounts. If we notice that many people try to abuse it, we will need to reconsider Free Tier altogether. \\nPlease play fair and purchase any Paid Subscription to continue.'}}"}

**Comment by muzammilzahid010** [comment]
any solution?
