### ISSUE TITLE
Circular import error in ElevenLabs 1.54.0 with Pydantic: ArrayJsonSchemaProperty not defined

### ISSUE THREAD

**Issue by gerimo** [elevenlabs/elevenlabs-python#501]
### Description

**Title**
Circular import error in ElevenLabs 1.54.0 with Pydantic: ArrayJsonSchemaProperty not defined

**Description**
I'm experiencing a circular import error in the ElevenLabs 1.54.0 library when trying to import the module. The error occurs between the array_json_schema_property.py and object_json_schema_property.py files within the elevenlabs.types package.

Environment
Python 3.10
ElevenLabs 1.54.0
Pydantic 1.10.21
pydantic-core 2.31.1
FastAPI 0.95.2

We are using the Conversation module, so downgrading to an earlier version of ElevenLabs is not an option.

### Code example

Traceback (most recent call last):
  File "/app.py", line 7, in <module>
    import elevenlabs
  File ".../elevenlabs/__init__.py", line 3, in <module>
    from .types import (
  File ".../elevenlabs/types/__init__.py", line 18, in <module>
    from .agent_config_api_model import AgentConfigApiModel
  File ".../elevenlabs/types/agent_config_api_model.py", line 5, in <module>
    from .array_json_schema_property import ArrayJsonSchemaProperty
  File ".../elevenlabs/types/array_json_schema_property.py", line 26, in <module>
    from .object_json_schema_property import ObjectJsonSchemaProperty  # noqa: E402
  File ".../elevenlabs/types/object_json_schema_property.py", line 29, in <module>
    update_forward_refs(ObjectJsonSchemaProperty)
  File ".../elevenlabs/core/pydantic_utilities.py", line 244, in update_forward_refs
    model.update_forward_refs(**localns)
  File "pydantic/main.py", line 815, in pydantic.main.BaseModel.update_forward_refs
  File "pydantic/typing.py", line 562, in pydantic.typing.update_model_forward_refs
  File "pydantic/typing.py", line 528, in pydantic.typing.update_field_forward_refs
  File "pydantic/typing.py", line 66, in pydantic.typing.evaluate_forwardref
  File ".../python3.10/typing.py", line 699, in _evaluate
    self.__forward_value__ = _eval_type(
  File ".../python3.10/typing.py", line 329, in _eval_type
    ev_args = tuple(_eval_type(a, globalns, localns, recursive_guard) for a in t.__args__)
  File ".../python3.10/typing.py", line 329, in <genexpr>
    ev_args = tuple(_eval_type(a, globalns, localns, recursive_guard) for a in t.__args__)
  File ".../python3.10/typing.py", line 329, in _eval_type
    ev_args = tuple(_eval_type(a, globalns, localns, recursive_guard) for a in t.__args__)
  File ".../python3.10/typing.py", line 329, in <genexpr>
    ev_args = tuple(_eval_type(a, globalns, localns, recursive_guard) for a in t.__args__)
  File ".../python3.10/typing.py", line 327, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File ".../python3.10/typing.py", line 699, in _evaluate
    self.__forward_value__ = _eval_type(
  File ".../python3.10/typing.py", line 329, in _eval_type
    ev_args = tuple(_eval_type(a, globalns, localns, recursive_guard) for a in t.__args__)
  File ".../python3.10/typing.py", line 329, in <genexpr>
    ev_args = tuple(_eval_type(a, globalns, localns, recursive_guard) for a in t.__args__)
  File ".../python3.10/typing.py", line 327, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File ".../python3.10/typing.py", line 694, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'ArrayJsonSchemaProperty' is not defined. Did you mean: 'ObjectJsonSchemaProperty'?

### Additional context
Steps to Reproduce
1. Install ElevenLabs 1.54.0 and Pydantic 1.10.21
Create a simple Python script that imports ElevenLabs
Run the script
What I've Tried
Different versions of Pydantic
Different Python versions (3.10, 3.11)
Adding pydantic-core explicitly
Using earlier versions of ElevenLabs (0.0.31 works without this error)
The issue appears to be a circular dependency between the two modules where each needs the other to be fully imported first.

_No response_

**Comment by AngeloGiacco** [comment]
Hi thanks for the issue, we will have a new release out soon which fixes this.

**Comment by flipsideview** [comment]
Is there any fix for this issue ? 
NameError: name 'ArrayJsonSchemaProperty' is not defined. Did you mean: 'ObjectJsonSchemaProperty'?

**Comment by gerimo** [comment]
I started using Python 3.10 and solved this.
ᐧ

**Comment by rbracco** [comment]
@AngeloGiacco any updates on timeline for the new release? I can't downgrade to a lower version.

**Comment by AngeloGiacco** [comment]
hi all, this is fixed in the latest release @rbracco @flipsideview @gerimo

**Comment by rbracco** [comment]
@AngeloGiacco I upgraded to 1.5.5 but I'm still experiencing a similar issue and opened #512, leaving it here in case anyone else is still stuck. Thank you.
